
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class BillHistory
{

    public int ID { get; set; }

    public int IDBill { get; set; }

    public System.DateTime DatePay { get; set; }

    public float TotalMoney { get; set; }

    public float MoneyCustomerPay { get; set; }

    public string IDDiscount { get; set; }

    public float Exchange { get; set; }



    public virtual Bill Bill { get; set; }

    public virtual Discount Discount { get; set; }

}

}
