
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class Bill
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Bill()
    {

        this.BillHistories = new HashSet<BillHistory>();

    }


    public int ID_Bill { get; set; }

    public System.DateTime TimeCheckIn { get; set; }

    public System.DateTime TimeCheckOut { get; set; }

    public string idEmployee { get; set; }

    public string idTable { get; set; }

    public float TotalMoney { get; set; }

    public bool statusBill { get; set; }



    public virtual Employee Employee { get; set; }

    public virtual TableFood TableFood { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BillHistory> BillHistories { get; set; }

}

}
