
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class Discount
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Discount()
    {

        this.BillHistories = new HashSet<BillHistory>();

    }


    public string ID_Discount { get; set; }

    public string NameDiscount { get; set; }

    public float DiscountRate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BillHistory> BillHistories { get; set; }

}

}
