
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class Food
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Food()
    {

        this.OrderTables = new HashSet<OrderTable>();

    }


    public string ID_Food { get; set; }

    public string NameFood { get; set; }

    public float Price { get; set; }

    public bool StatusFood { get; set; }

    public string IDCategory { get; set; }

    public int QuantityFood { get; set; }

    public string PictureFood { get; set; }



    public virtual FoodCategory FoodCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderTable> OrderTables { get; set; }

}

}
