
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class OrderTable
{

    public string ID_Order { get; set; }

    public string IDFood { get; set; }

    public int Quantity { get; set; }

    public string IDTable { get; set; }



    public virtual Food Food { get; set; }

    public virtual TableFood TableFood { get; set; }

}

}
