
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class Revenue
{

    public string ID_Revenue { get; set; }

    public System.DateTime RevenueInDate { get; set; }

    public float TotalInDate { get; set; }

    public int NumberOfBill { get; set; }

    public int NumberOfCustomer { get; set; }

}

}
