
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PBL03
{

using System;
    using System.Collections.Generic;
    
public partial class WorkSchedule
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WorkSchedule()
    {

        this.Salaries = new HashSet<Salary>();

        this.TimeSheets = new HashSet<TimeSheet>();

    }


    public int ID_Schedule { get; set; }

    public string IDEmployee { get; set; }

    public int IDShift { get; set; }

    public System.DateTime DateWork { get; set; }

    public string Note { get; set; }



    public virtual Employee Employee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Salary> Salaries { get; set; }

    public virtual ShiftWork ShiftWork { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TimeSheet> TimeSheets { get; set; }

}

}
